#pragma once

#define NOMINMAX

#define REPORT_FILE_NAME "report.log"

#define MAX_LOADSTRING 100

#define DRUM_CHANNEL 9

#define DEFAULT_TEMPO 500000
#define DEFAULT_BPM 120

#define MIDI_FORMAT_SINGLE 0
#define MIDI_FORMAT_SYNC_MULTI 1
#define MIDI_FORMAT_ASYNC 2
